export const RECEIVE_PRODUCTS = "RECEIVE_PRODUCTS";
export const RECEIVE_FILTERS = "RECEIVE_FILTERS";
export const TOGGLE_FILTERS = "TOGGLE_FILTERS";
export const RECEIVE_FILTERED_PRODUCTS = "RECEIVE_FILTERED_PRODUCTS";
export const TOGGLE_PRODUCTS_IN_BASKET = "TOGGLE_PRODUCTS_IN_BASKET";
export const TOGGLE_LOADER = "TOGGLE_LOADER";